// Import your Wasm wrapper (generated by wasm-pack)
importScripts('./pkg/synthesis_engine.js'); 

self.onmessage = async (e) => {
    if (e.data.type === 'CAPTURE_INTENT') {
        const { dwellDuration, target } = e.data.data;
        
        // Execute Desktop-Class Synthesis (Wasm function)
        const layoutSchema = wasm_calculate_layout(dwellDuration, target);
        
        self.postMessage({ type: 'APPLY_LAYOUT', layout: layoutSchema });
    }
};
